# Generated by Django 5.2.4 on 2025-07-06 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacidad_a', models.FloatField()),
                ('capacidad_b', models.FloatField()),
                ('producto_a', models.IntegerField()),
                ('producto_b', models.IntegerField()),
                ('ingreso_total', models.FloatField()),
            ],
        ),
    ]
